spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/mycrm.db

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: indi.nonoas.crm.beans
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


logging:
  level:
    indi:
      nonoas:
        crm:
          dao: error

