spring:
  application:
    name: mycrm
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/mycrm
    username: root
    password: 20210710mycrm
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-spring.xml


